### ISSUE TITLE
FileNotFoundException 

### ISSUE THREAD

**Issue by sujitpanda** [Ponsen/SpeechRecognizer#1]
I am getting FileNotFoundException when accessing the audio.raw from assert folder .

**Comment by Ponsen** [comment]
Hi sujitpanda,

this problem has nothing to do with this example project.

Anyway, I've checked your fork and found the issue.
In Mainactivity::createFileFromInputStream this should do the trick (or something similar):

> File f = File.createTempFile(my_file_name,"raw");
